import type { Metadata } from "next";
import Link from "next/link";
import { ArrowIcon } from "@/components/icons";

export const metadata: Metadata = { title: "Industries", description: "VIoT connected-vehicle systems for mining fleets, commercial and logistics fleets, and OEM manufacturing programmes.", alternates: { canonical: "/industries" } };
const industries = [
  ["01 / PRIORITY MARKET", "Mining operations", "Weak signal, unstable power, dust, vibration and long shifts make mining the right place to prove a reliable data path.", ["Device health and continuous reporting", "Geofenced operating areas", "Panic, tamper and movement exceptions", "Field-ready power and enclosure design"]],
  ["02 / COMMERCIAL", "Logistics fleets", "Connect location, cargo security and vehicle condition for ordinary day-to-day fleet operations and last-mile movement.", ["Live trips and vehicle status", "Container and cargo e-lock events", "Route and zone exceptions", "ERP / TMS data integration"]],
  ["03 / MANUFACTURING", "OEM programmes", "Install telematics at the point of manufacture so vehicles leave the line connected to a platform from day one.", ["Hardware + platform bundle", "Integration support", "Production-line deployment planning", "Ongoing device monitoring"]],
];
export default function IndustriesPage() { return <><section className="page-hero"><div className="container"><p className="breadcrumb">Industries / Deployment models</p><h1>Built for the conditions that expose <em>weak systems.</em></h1><p className="page-lede">VIoT starts with the operating environment, then matches the device, data path and platform workflow to it.</p></div></section><section className="section"><div className="container"><div className="split-heading"><div><p className="eyebrow dark"><span />Current focus</p><h2>Three markets. Specific jobs.</h2></div><p>These are the deployment models VIoT is actively building for today. We do not list a sector until the hardware and workflow have a clear job there.</p></div><div className="industry-page-grid">{industries.map(([label, title, copy, points]) => <article className="industry-panel" key={title as string}><p className="section-index">{label as string}</p><div><h2>{title as string}</h2><p>{copy as string}</p><ul>{(points as string[]).map((point) => <li key={point}>{point}</li>)}</ul></div></article>)}</div></div></section><section className="cta-band"><div className="container cta-grid"><div><p className="eyebrow"><span />Fit before pitch</p><h2>Start with the field conditions.</h2></div><div><p>Tell us the fleet size, operating environment, current devices and the data gap. We will map the right starting point.</p><Link className="button button-primary" href="/contact">Describe the operation <ArrowIcon /></Link></div></div></section></>; }
